# Generated by Django 4.1.5 on 2023-01-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='title_two',
            new_name='content',
        ),
    ]
