# Generated by Django 4.1.5 on 2023-01-27 11:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
